[package]
name = "eta_obj_pool"
version = "1.0.0"
edition = "2021"
authors = ["erik9631@gmail.com"]
description = "Thread safe object pool"
license-file = "license.txt"
readme = "README.MD"


[lib]
path = "src/lib.rs"

[dependencies]
crossbeam = "0.8.4"
